title: CV Arxiv Daily
description: Automatically Update Interested Papers Daily using Github Actions (Update Every 8th hours)
show_downloads: true

github:
  zip_url: https://github.com/youngjetduan/cv-arxiv-daily
  another_url: https://github.com/youngjetduan/cv-arxiv-daily

## add remote theme
# remote_theme: jekyll/minima@v2.5.1
remote_theme: pages-themes/primer@v0.6.0

# minima:
skin: dark
social_links:
  twitter: AlphaRealcat
  github: youngjetduan

plugins:
 - jekyll-remote-theme # add this line to the plugins list if you already have one
 - jekyll-feed
 - jekyll-seo-tag
